# Generated by Django 2.0.1 on 2018-01-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningMaterials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('tags', models.CharField(blank=True, max_length=300, null=True)),
                ('is_translated', models.BooleanField(default=False)),
                ('source_language', models.CharField(default='None', max_length=4)),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('translated_file', models.FileField(blank=True, null=True, upload_to='translated/')),
                ('original_file', models.FileField(upload_to='original/')),
                ('date_uploaded', models.DateField(auto_now=True)),
                ('category', models.CharField(choices=[('all_level', 'All Level'), ('grade_level', 'Grade Level'), ('kinder_level', 'Kind Level')], default='all_level', max_length=12)),
            ],
        ),
    ]
