# Generated by Django 2.0.1 on 2018-02-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_learningmaterials_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learningmaterials',
            old_name='title',
            new_name='original_title',
        ),
        migrations.AddField(
            model_name='learningmaterials',
            name='translated_title',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='learningmaterials',
            name='category',
            field=models.CharField(choices=[('All Level', 'All Level'), ('Grade Level', 'Grade Level'), ('Kinder Level', 'Kind Level')], default='All Level', max_length=12),
        ),
    ]
